export const API_ENDPOINTS = {
  LOGIN: '/User/LogIn',
  REGISTER: '/User/Register',
  LOGOUT: '/User/LogOut',
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES: '/Category/GetInPowerCategories',
  DIETARY: '/dietary.json',
  BRANDS: '/brands.json',
  PRODUCTS: '/Product/GetInPowerProducts',
  PRODUCT: '/Product/GetProduct',
  RELATED_PRODUCTS: '/Product/GetProductByCategoryId',
  BEST_SELLER_PRODUCTS: '/products_best_seller.json',
  BEST_SELLER_GROCERY_PRODUCTS: '/products_best_seller_grocery.json',
  POPULAR_PRODUCTS: '/products_popular.json',
  COOKIES_PRODUCTS: '/products_cookies.json',
  CHIPS_PRODUCTS: '/products_chips.json',
  POPCORN_JERKY_PRODUCTS: '/products_popcorn_jerky.json',
  FRESH_VEGETABLES_PRODUCTS: '/products_fresh_vegetables.json',
  SEARCH: '/Product/SearchProduct',
  ORDERS: '/orders.json',
  ORDER: '/order.json',
  ORDER_STATUS: 'api/Library/GetOrderStatuses',
  ADDRESS: '/address.json',
  PAYMENT: '/payment.json',
  CONTACT: '/contact.json',
  SHOP: '/shop.json',
  SHOPS: '/shops.json',
  WISHLIST: '/wishlist.json',
  ADDPRODUCT:'/Product/SendProductRequest',
  LOGGEDUSER:'/User/GetLoggedUser',
  USERPRODUCT:'/Product/GetUserProductLogs',

};
